# .github/workflows/pharo-data.yml
name: Pharo Data Generation

on:
  push:
    branches:
      - test-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [Moose64-11]
    name: ${{ matrix.smalltalk }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup SmalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Verify VM and Image Installation
        run: |
          echo "Checking if VM exists at $SMALLTALK_CI_VM"
          if [ ! -f "$SMALLTALK_CI_VM" ]; then
            echo "VM not found. Exiting."
            exit 1
          fi
          echo "Checking if Image exists at $SMALLTALK_CI_IMAGE"
          if [ ! -f "$SMALLTALK_CI_IMAGE" ]; then
            echo "Image not found. Exiting."
            exit 1
          fi

      - name: Generate pharo data
        run: |
          ls -l /home/runner/.smalltalkCI/_builds
          $SMALLTALK_CI_VM $SMALLTALK_CI_IMAGE eval "| data filePath writer |
          data := #((#'ID' #'Name' #'Age') (1 'Alice' 30) (2 'Bob' 25) (3 'Charlie' 35)).
          filePath := 'exported_', Date today yyyymmdd, '.csv'.
          writer := NeoCSVWriter on: filePath asFileReference writeStream.
          writer nextPutAll: data.
          writer close."

      - name: Move csv to folder
        run: |
          mkdir -p pharo-data
          mv *.csv pharo-data

      - name: Push to current branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pharo-data
          git commit -m "Update pharo-data for branch ${{ github.ref_name }}"
          git push origin HEAD:refs/heads/${{ github.ref_name }}
